name: Update Property value
description: update properties value
author: Anbazhagan Natarajan
branding:
  icon: 'edit'
  color: 'blue'
inputs:
  source_path:
    description: 'The path to the source file to be copied.'
    required: true
  properties:
    description: 'The property keys you want to write. Accepts an array using comma separator.'
    required: true
  values:
    description: 'The property values you want to write (same order as the keys). Accepts an array using comma separator.'
    required: true
  replace_tokens:
    description: 'The property values to replace special char. example, if the secrets contains EQUALTO and if you would like to replace as = then pass EQUALTO:= this will replace EQUALTO occurances in values and replace with =' 
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source_path }}
    - ${{ inputs.properties }}
    - ${{ inputs.values }}
    - ${{ inputs.replace_tokens }}
